{% set version = "1.2.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapproj
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mapproj_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mapproj/mapproj_{{ version }}.tar.gz
  sha256: da28fab490072e0b2ff5e124092d6b3146e4c01b2386e23a2ea4b0e9fc72df82

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-maps >=2.3_0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-maps >=2.3_0

test:
  commands:
    - $R -e "library('mapproj')"           # [not win]
    - "\"%R%\" -e \"library('mapproj')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mapproj
  license: Lucent Public License
  summary: Converts latitude/longitude into projected coordinates.
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
