{% set version = "1.2.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mapproj
  version: {{ version|replace("-", "_") }}

source:
  fn: mapproj_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mapproj_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mapproj/mapproj_{{ version }}.tar.gz
  sha256: 62a5aa97837ae95ef9f973d95fe45fe43dbbf482dfa922e9df60f3c510e7efe5

build:
  merge_build_host: True  # [win]
  number: 1
  # r-maps is missing in win64 as well
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-maps >=2.3_0

  run:
    - r-base
    - r-maps >=2.3_0

test:
  commands:
    - $R -e "library('mapproj')"  # [not win]
    - "\"%R%\" -e \"library('mapproj')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mapproj
  license: Lucent Public
  summary: Converts latitude/longitude into projected coordinates.
  license_family: OTHER

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
