appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KcWuOMYm0S3rXpcZEAaxFdWN/Uikvvatwlkk1zctPWiQUT56a3QH5HG+mmRNlwZ+GHYJIZE3dx1DSG4eQnGfDLVqmcMcvq9HmDtwZdeS9jQ7/UgSS2CLu1ALd8WzjDe+9v5j+Ee7IH5+CmnGh6SPthicNgB+3YC+C6lCsdzshdlw1WNuvQCE1LlEoHl9DgsIlzxP/1nPQwHBppMyN+1h4isqYcw2M0L2fp8z2x1oq/4MSYUHLXX3H8K03Q1/001RoNRjC8yTg2L8KXjURQA5L33TCK5FbPh0YlqqeSw9QJUPPoytBExHnegPf+HFNCNV2rtXVuICQ5NAl3OEnKGbJHAOY9SW1xZ7Lhr9YXial979fQxM75qNl98cOCAhuYlHrpX7cMPuzQPlyrVborOOwC4tcXfMEHz3OffD6bSf6/OjXuvTNT1bxqcyv6HagCQArAVsOAeyL7tFO0TSMs0Ma6Maga79N/IkxuAZx2XLb26YDRkion65dcVgzG0Rznqw73L5UmpE4vDN/WnQI1b/sk+vOmVeqIABeSE9yTwJ8KE4+2m0v647Wu2j48G8M7JJXHl1HrapjTAWmaKkn0hz2MtfLRAquyH9XZUnersQfBrxEKARFx8XJXeMs03N5rOeWqSvec9N0dlfj/NT5xbAltoZpISXr/DEKeH3xALTlSY=}
